name: pgDump Action
description: GitHub Action for creating a dump of a database's contents

inputs:
  postgres-version:
    required: true
  connection-string:
    required: true

runs:
  using: composite
  steps:
    - run: |
        docker container run \
          --name action-postgres \
          -d \
          postgres:${{ inputs.postgres-version }}
      shell: bash
    - run: |
        docker container exec \
          action-postgres \
          pg_dump -d ${{ inputs.connection-string }} > /tmp/backup.sql
      shell: bash

branding:
  icon: database
  color: blue
